### ISSUE TITLE
Create Build docs

### ISSUE THREAD

**Issue by geoghegan** [theksmith/CarBusInterface#3]
It would be really nice if there were step by step build docs for new users. Currently it's guess work.

**Comment by theksmith** [comment]
not sure what is needed? there was a change in gradle with the newer versions of android studio preventing the project from building (fixed in v0.9) - but in general you just open the main project in Android Studio and click on Build  > Make Project.

i did add the following note in the latest README.md:
- The project is currently setup for Android Studio 1.2.1.1. If you get build errors, be sure you are opening the folder "Android Studio Project", not this root folder!

**Comment by theksmith** [comment]
closing for now, re-open if you have specific ideas for what should be provided
